### ISSUE TITLE
Таблица в коментах

### ISSUE THREAD

**Issue by mrAntiUser** [mrAntiUser/JRAS#84]
В посте http://old.reactor.cc/post/4476242 таблица в коментах косячит из-за класса 
```
.video_gif_holder {
    display: inline-block;
}
```
Он в свою очередь сделан для восстановления "ссылка на гифку"

**Comment by mrAntiUser** [comment]
влияет именно задание высоты в классе
```css
.article .ufoot span, .article .ufoot span a {
  line-height: 18px;
  height: 18px;
}
```
